spring.application.name=api
jwt.secret=${JWT_SECRET:Kf9s8d7f6sdf87sdf98sdf87sdf98sdf87sdf==}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5432/dignamente_db_arq
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true